# Generated by Django 4.1.2 on 2022-12-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_missing', models.DateField(null=True)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('age_at_missing', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=45, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('race', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
