# Generated by Django 4.1.2 on 2022-11-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humantrafficking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
