# Generated by Django 4.1.2 on 2022-12-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humantrafficking', '0002_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
    ]
